language: node_js
node_js:
  - "13"

services:
  - docker

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
  - docker-compose -f docker-compose-build.yaml build

after_success:
  - docker push mmauren/udagram-api-feed push
  - docker push mmauren/udagram-api-user push
  - docker push mmauren/udagram-frontend push
  - docker push mmauren/reverseproxy push

# env:
#   global:
#     - DOCKER_USERNAME=<your-dockerhub-username>
#     - DOCKER_PASSWORD=<your-dockerhub-password>