apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-feed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-feed
  template:
    metadata:
      labels:
        app: backend-feed
    spec:
      containers:
      - name: backend-feed
        image: mmauren/udagram-api-feed
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: udagram-config
        - secretRef:
            name: postgres-secrets
        volumeMounts:
        - name: aws-secrets
          mountPath: /root/.aws
      volumes:
      - name: aws-secrets
        hostPath:
          path: /root/.aws
